name: CI

on:
  # push:
  #   branches: [ '**' ]
  # pull_request:
  #   branches: [ '**' ]
  workflow_dispatch:
permissions:
  contents: read
  packages: read
  # To report GitHub Actions status checks
  statuses: write
jobs:
  python:
    uses: chenette/workflow/.github/workflows/main.yml@main
    with:
      environment: dev
      application_type: python
